### ISSUE TITLE
Witch's potion script doesn't end when completed.

### ISSUE THREAD

**Issue by NotSinan** [NotSinan/DreamBotQuester#27]
When quest complete, script is still running.

**Comment by Dreambotter420** [comment]
This is because of the Quest branch checking if Quest is finished before executing the FinishedQuestLeaf inside the Quest branch: 

`return FreeQuest.WITCHS_POTION.hasRequirements() && !FreeQuest.WITCHS_POTION.isFinished();`

To resolve this, we can apply a check inside the isValid method of the Quest branch, which checks for requirements and finished status, then call `ScriptManager.getScriptManager().stop();` and return false if requirements are not met or quest is finished, then afterwards return true to execute Quest branch if the quest can be performed.

**Comment by Dreambotter420** [comment]
For example: 

`@Override
    public boolean isValid() {
        if(FreeQuest.WITCHS_POTION.hasRequirements()) {
            Logger.log("Do not have requirements to start Witch's Potion, stopping script...!");
            ScriptManager.getScriptManager().stop();
            return false;
        }

        if(FreeQuest.WITCHS_POTION.isFinished()) {
            Logger.log("Finished Witch's Potion, stopping script...!");
            ScriptManager.getScriptManager().stop();
            return false;
        }

        return true;
    }`

**Comment by NotSinan** [comment]
> For example:
> 
> @OverRide public boolean isValid() { if(FreeQuest.WITCHS_POTION.hasRequirements()) { Logger.log("Do not have requirements to start Witchs Potion, stopping script...!"); ScriptManager.getScriptManager().stop(); return false; }
> 
> ```
>     if(FreeQuest.WITCHS_POTION.isFinished()) {
>         Logger.log("Finished Witchs Potion, stopping script...!");
>         ScriptManager.getScriptManager().stop();
>         return false;
>     }
> 
>     return true;
> }
> ```

I think this is perfect

**Comment by Dreambotter420** [comment]
Added class CheckRequirements and method checkRequirements(Quest quest) that implements this method and revised all Quest branches to implement this in next commit.
